In [1]:
import sklearn
from sklearn.cluster import KMeans
import nltk
import numpy as np
import pickle
from nltk.tokenize import word_tokenize
from tqdm import tqdm

In [2]:
import tensorflow as tf
from training.model.config1 import Config
from training.model.ner_model1 import NERModel
from training.model.data_utils1 import CoNLLDataset, get_vocabs, UNK, NUM, \
    get_glove_vocab, write_vocab, load_vocab, get_char_vocab, \
    export_trimmed_glove_vectors, get_processing_word


In [3]:
#import files created in preprocessing
sent_embed_list = pickle.load(open ("sent_embed_list.p", "rb"))
sent_id_dict = pickle.load(open ("sent_id_dict.p", "rb"))
sent_list = pickle.load(open ("sent_list.p", "rb"))
sent_label_conf_pos_from_folds = pickle.load(open ("sent_label_conf_pos_from_folds.p", "rb"))
sent_with_num2orig_sent_dict = pickle.load(open ("sent_with_num2orig_sent_dict.p", "rb"))


embedding_len = 200

In [8]:
#initiate the KMeans input matrix
X = np.zeros((len(sent_id_dict),embedding_len), dtype=float)
#print(len(sent_id_dict))
print(X.shape)
print(X)

(40822, 200)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
#populate the KMeans input matrix with sentence embeddings created in preprocessing
for i in range(len(X)):
    X[i] = X[i] + sent_embed_list[i]

In [10]:
#check matrix dimentions 
print(X.shape)
#X = X[0:1000,:] #used for prototyping to create a smaller dataset
print(X.shape)

(40822, 200)
(40822, 200)


In [11]:
#initiate tf session
tf.reset_default_graph()
config = Config()
print('Config')    
model = NERModel(config)
model.build()

Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


In [13]:
#tuning of two hyperparameters: 
#k - number of clusters for kMeans
#percentage - % of the cluster to be used as training data 

k_list = [10,100,200]
percentage_list = [10,30,50]


for k in k_list:
    for percentage in percentage_list:
        #create the training dataset based on kMeans clusters and prediction confidence
        sentences_for_training = []
        kmeans = KMeans(n_clusters=k, random_state=0).fit(X)
        labels = kmeans.predict(X)
        sent_cluster_dict = {}
        for i in range(len(X)):
            sent_cluster_dict[' '.join(sent_list[i])] = labels[i]
        cluster_sent_dict = {}
        for key, value in sorted(sent_cluster_dict.items()):
            cluster_sent_dict.setdefault(value, []).append(key)
        
        for key in cluster_sent_dict:
            conf_dict = {}
            for sent in cluster_sent_dict[key]:
                if len(sent) > 0:
                    conf_dict[sent] = sent_label_conf_pos_from_folds[sent][-1]['confidence']
            number_of_sent = round(float(len(cluster_sent_dict[key])) * float(percentage) / 100.0)
            if number_of_sent == 0:
                number_of_sent = 1 #have a minimum of 1 sent per cluster           
            training_sent_list = sorted(conf_dict.items(), key=lambda x:-x[1])[:number_of_sent]
            for sentence in training_sent_list:
                sentences_for_training.append(sentence[0])

        #make conll-like data based on the training data created above
        fout = open('kMeans_data/train_k=%s_percentage=%s.txt' %(k, percentage), 'w')
        for sentence in sentences_for_training:
            words = sentence.split(" ")
            pos = sent_label_conf_pos_from_folds[sentence][1]['pos_tags']
            labels = sent_label_conf_pos_from_folds[sentence][0]['labels']
            #print(words, len(words))
            #print(pos, len(pos))
            #print(labels, len(labels)) 
            #print('\n')
            for i in range(len(words)):
                fout.write('%s %s %s\n' %(words[i], pos[i], labels[i]))
            fout.write('\n')
        
        
        
        #build support data and train and evaluate using the created datset
        processing_word = get_processing_word(lowercase=True)
        print('Processing_word')
        train = CoNLLDataset('kMeans_data/train_k=%s_percentage=%s.txt' %(k, percentage), processing_word)
        dev   = CoNLLDataset('kMeans_data/dev.txt', processing_word)
        #test  = CoNLLDataset('kMeans_data/dev.txt', processing_word)

        vocab_words, vocab_tags = get_vocabs([train, dev])
        vocab_glove = get_glove_vocab(config.filename_glove)
        vocab = vocab_words & vocab_glove
        vocab.add(UNK)
        vocab.add(NUM)

        # Save vocab
        write_vocab(vocab, config.filename_words)
        write_vocab(vocab_tags, config.filename_tags)

        # Trim GloVe Vectors
        vocab = load_vocab(config.filename_words)
        export_trimmed_glove_vectors(vocab, config.filename_glove,
                                    config.filename_trimmed, config.dim_word)

        #Build and save char vocab
        train = CoNLLDataset('kMeans_data/train_k=%s_percentage=%s.txt' %(k, percentage))
        vocab_chars = get_char_vocab(train)
        write_vocab(vocab_chars, config.filename_chars)
        
        #training
       # config = Config(load=True)
        
        

        dev   = CoNLLDataset('kMeans_data/dev.txt', config.processing_word,
                         config.processing_tag, config.max_iter)
        train = CoNLLDataset('kMeans_data/train_k=%s_percentage=%s.txt' %(k, percentage), config.processing_word,
                         config.processing_tag, config.max_iter)
        # train model
        print('training')
        print("hyperparam for the training below: %", percentage, "k", k)
        model.train(train, dev)
        
        tf.reset_default_graph()
        config = Config()
        print('Config')    
        model = NERModel(config)
        model.build()
        
    
        

Processing_word
Building vocab...
- done. 25082 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 16056 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 84 tokens
training
hyperparam for the training below: % 10 k 10


Epoch 1 out of 15


204/204 [==============================] - 100s - train loss: 22.6613   


f1 0.49 - p 0.70 - r 0.44


7812.0 10454.0
o: f1=0.37  p=0.75  r=0.25
12690.0 18649.0
p: f1=0.53  p=0.68  r=0.43
167048.0 225803.0
N: f1=0.83  p=0.74  r=0.96
3434.0 5289.0
i: f1=0.23  p=0.65  r=0.14
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  7812    679  22853    291]
 [    90  12690  16156    303]
 [  2434   3949 167048   1261]
 [   118   1331  19746   3434]]


- new best score!
Epoch 2 out of 15


204/204 [==============================] - 108s - train loss: 12.7758   


f1 0.57 - p 0.68 - r 0.53


11156.0 15793.0
o: f1=0.47  p=0.71  r=0.35
18363.0 31677.0
p: f1=0.60  p=0.58  r=0.63
158349.0 203706.0
N: f1=0.84  p=0.78  r=0.91
5954.0 9019.0
i: f1=0.35  p=0.66  r=0.24
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11156   1331  18946    202]
 [   167  18363  10437    272]
 [  4223   9529 158349   2591]
 [   247   2454  15974   5954]]


- new best score!
Epoch 3 out of 15


204/204 [==============================] - 107s - train loss: 9.0478   


f1 0.59 - p 0.66 - r 0.57


11674.0 16549.0
o: f1=0.48  p=0.71  r=0.37
21281.0 41307.0
p: f1=0.60  p=0.52  r=0.73
151360.0 189185.0
N: f1=0.83  p=0.80  r=0.87
8203.0 13154.0
i: f1=0.43  p=0.62  r=0.33
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11674   1604  17937    420]
 [   172  21281   7459    327]
 [  4392  14736 151360   4204]
 [   311   3686  12429   8203]]


- new best score!
Epoch 4 out of 15


204/204 [==============================] - 103s - train loss: 6.9255   


f1 0.61 - p 0.66 - r 0.59


12558.0 18030.0
o: f1=0.51  p=0.70  r=0.40
21007.0 39422.0
p: f1=0.61  p=0.53  r=0.72
150446.0 186215.0
N: f1=0.83  p=0.81  r=0.86
9861.0 16528.0
i: f1=0.48  p=0.60  r=0.40
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12558   1506  17055    516]
 [   190  21007   7589    453]
 [  4918  13630 150446   5698]
 [   364   3279  11125   9861]]


- new best score!
Epoch 5 out of 15


204/204 [==============================] - 119s - train loss: 5.8038   


f1 0.63 - p 0.66 - r 0.61


15669.0 24434.0
o: f1=0.56  p=0.64  r=0.50
19422.0 32465.0
p: f1=0.63  p=0.60  r=0.66
151109.0 185756.0
N: f1=0.84  p=0.81  r=0.87
10490.0 17540.0
i: f1=0.50  p=0.60  r=0.43
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 15669   1109  14400    457]
 [   381  19422   8878    558]
 [  7841   9707 151109   6035]
 [   543   2227  11369  10490]]


- new best score!
Epoch 6 out of 15


204/204 [==============================] - 122s - train loss: 5.0017   


f1 0.64 - p 0.66 - r 0.62


18943.0 35280.0
o: f1=0.57  p=0.54  r=0.60
17661.0 26062.0
p: f1=0.64  p=0.68  r=0.60
147256.0 180213.0
N: f1=0.83  p=0.82  r=0.84
11022.0 18640.0
i: f1=0.51  p=0.59  r=0.45
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 18943    898  11273    521]
 [   530  17661  10402    646]
 [ 14799   6186 147256   6451]
 [  1008   1317  11282  11022]]


- new best score!
Epoch 7 out of 15


204/204 [==============================] - 139s - train loss: 4.6383   


f1 0.63 - p 0.69 - r 0.59
Epoch 8 out of 15


16897.0 27163.0
o: f1=0.57  p=0.62  r=0.53
16125.0 22415.0
p: f1=0.62  p=0.72  r=0.55
156630.0 195670.0
N: f1=0.85  p=0.80  r=0.90
9521.0 14947.0
i: f1=0.48  p=0.64  r=0.39
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 16897    694  13732    312]
 [   515  16125  12058    541]
 [  8950   4539 156630   4573]
 [   801   1057  13250   9521]]
204/204 [==============================] - 68s - train loss: 3.9317    


f1 0.61 - p 0.71 - r 0.56
Epoch 9 out of 15


14756.0 22341.0
o: f1=0.55  p=0.66  r=0.47
15313.0 20800.0
p: f1=0.61  p=0.74  r=0.52
160975.0 204871.0
N: f1=0.85  p=0.79  r=0.92
8213.0 12183.0
i: f1=0.45  p=0.67  r=0.33
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 14756    608  15994    277]
 [   397  15313  13148    381]
 [  6565   3840 160975   3312]
 [   623   1039  14754   8213]]
204/204 [==============================] - 68s - train loss: 3.3851    


f1 0.63 - p 0.70 - r 0.59
- early stopping 3 epochs without improvement


17228.0 27853.0
o: f1=0.58  p=0.62  r=0.54
16219.0 22570.0
p: f1=0.63  p=0.72  r=0.55
156834.0 196193.0
N: f1=0.85  p=0.80  r=0.90
8881.0 13579.0
i: f1=0.46  p=0.65  r=0.36
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 17228    702  13421    284]
 [   445  16219  12129    446]
 [  9335   4555 156834   3968]
 [   845   1094  13809   8881]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 32661 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 19481 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 86 tokens
training
hyperparam for the training below: % 30 k 10


Epoch 1 out of 15


612/612 [==============================] - 174s - train loss: 14.4909   


f1 0.62 - p 0.71 - r 0.58


11960.0 20876.0
i: f1=0.53  p=0.57  r=0.49
159135.0 201258.0
N: f1=0.85  p=0.79  r=0.91
10602.0 13886.0
o: f1=0.47  p=0.76  r=0.34
17138.0 24175.0
p: f1=0.64  p=0.71  r=0.59
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11960  11681    187    801]
 [  7208 159135   3034   5315]
 [   634  19478  10602    921]
 [  1074  10964     63  17138]]


- new best score!
Epoch 2 out of 15


612/612 [==============================] - 173s - train loss: 6.7587   


f1 0.65 - p 0.71 - r 0.61


12548.0 21517.0
i: f1=0.54  p=0.58  r=0.51
157191.0 195296.0
N: f1=0.85  p=0.80  r=0.90
13326.0 18052.0
o: f1=0.54  p=0.74  r=0.42
17777.0 25330.0
p: f1=0.65  p=0.70  r=0.61
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12548  10967    276    838]
 [  7373 157191   4320   5808]
 [   533  16869  13326    907]
 [  1063  10269    130  17777]]


- new best score!
Epoch 3 out of 15


612/612 [==============================] - 173s - train loss: 4.4534   


f1 0.65 - p 0.70 - r 0.63


11224.0 17926.0
i: f1=0.53  p=0.63  r=0.46
154692.0 189533.0
N: f1=0.85  p=0.82  r=0.89
15605.0 22221.0
o: f1=0.58  p=0.70  r=0.49
19656.0 30515.0
p: f1=0.66  p=0.64  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11224  11505    415   1485]
 [  5657 154692   6027   8316]
 [   421  14551  15605   1058]
 [   624   8785    174  19656]]


- new best score!
Epoch 4 out of 15


612/612 [==============================] - 178s - train loss: 3.2826   


f1 0.66 - p 0.68 - r 0.65


13089.0 22527.0
i: f1=0.56  p=0.58  r=0.53
150429.0 181408.0
N: f1=0.84  p=0.83  r=0.86
16189.0 23467.0
o: f1=0.59  p=0.69  r=0.51
20341.0 32793.0
p: f1=0.66  p=0.62  r=0.70
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 13089   9482    446   1612]
 [  7931 150429   6641   9691]
 [   614  13683  16189   1149]
 [   893   7814    191  20341]]


- new best score!
Epoch 5 out of 15


612/612 [==============================] - 344s - train loss: 2.6082   


f1 0.64 - p 0.68 - r 0.63
Epoch 6 out of 15


11780.0 19138.0
i: f1=0.54  p=0.62  r=0.48
152152.0 186021.0
N: f1=0.84  p=0.82  r=0.87
13829.0 19509.0
o: f1=0.54  p=0.71  r=0.44
20988.0 35527.0
p: f1=0.65  p=0.59  r=0.72
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11780  10474    369   2006]
 [  6222 152152   5161  11157]
 [   499  15931  13829   1376]
 [   637   7464    150  20988]]
612/612 [==============================] - 322s - train loss: 2.1838   


f1 0.63 - p 0.71 - r 0.59
Epoch 7 out of 15


10982.0 17457.0
i: f1=0.52  p=0.63  r=0.45
158330.0 198332.0
N: f1=0.85  p=0.80  r=0.91
11056.0 14785.0
o: f1=0.48  p=0.75  r=0.35
19635.0 29621.0
p: f1=0.67  p=0.66  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10982  11965    200   1482]
 [  5460 158330   3410   7492]
 [   490  19077  11056   1012]
 [   525   8960    119  19635]]
612/612 [==============================] - 325s - train loss: 1.8324   


f1 0.65 - p 0.70 - r 0.62
- early stopping 3 epochs without improvement


11208.0 18099.0
i: f1=0.52  p=0.62  r=0.46
156200.0 192465.0
N: f1=0.85  p=0.81  r=0.89
14798.0 20801.0
o: f1=0.56  p=0.71  r=0.47
19322.0 28830.0
p: f1=0.67  p=0.67  r=0.66
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11208  11764    353   1304]
 [  5806 156200   5484   7202]
 [   414  15421  14798   1002]
 [   671   9080    166  19322]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 37221 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 21306 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 87 tokens
training
hyperparam for the training below: % 50 k 10


Epoch 1 out of 15


1020/1020 [==============================] - 450s - train loss: 14.0480   


f1 0.64 - p 0.72 - r 0.60


11228.0 17777.0
i: f1=0.53  p=0.63  r=0.46
159401.0 198954.0
N: f1=0.85  p=0.80  r=0.91
12031.0 15722.0
o: f1=0.51  p=0.77  r=0.38
18830.0 27742.0
p: f1=0.66  p=0.68  r=0.64
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11228  12038    197   1166]
 [  5281 159401   3414   6596]
 [   538  17916  12031   1150]
 [   730   9599     80  18830]]


- new best score!
Epoch 2 out of 15


1020/1020 [==============================] - 488s - train loss: 5.6124   


f1 0.66 - p 0.73 - r 0.62


12276.0 19489.0
i: f1=0.56  p=0.63  r=0.50
158707.0 195443.0
N: f1=0.86  p=0.81  r=0.91
13393.0 17556.0
o: f1=0.54  p=0.76  r=0.42
19496.0 27707.0
p: f1=0.68  p=0.70  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12276  10993    211   1149]
 [  5974 158707   3825   6186]
 [   513  16853  13393    876]
 [   726   8890    127  19496]]


- new best score!
Epoch 3 out of 15


1020/1020 [==============================] - 484s - train loss: 3.4403   


f1 0.67 - p 0.71 - r 0.64


12615.0 20367.0
i: f1=0.56  p=0.62  r=0.51
155597.0 189703.0
N: f1=0.85  p=0.82  r=0.89
14877.0 20522.0
o: f1=0.57  p=0.72  r=0.47
20089.0 29603.0
p: f1=0.68  p=0.68  r=0.69
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12615  10564    336   1114]
 [  6485 155597   5153   7457]
 [   503  15312  14877    943]
 [   764   8230    156  20089]]


- new best score!
Epoch 4 out of 15


1020/1020 [==============================] - 526s - train loss: 2.4719   


f1 0.66 - p 0.71 - r 0.64
Epoch 5 out of 15


12756.0 20847.0
i: f1=0.56  p=0.61  r=0.52
155451.0 189644.0
N: f1=0.85  p=0.82  r=0.89
14538.0 19917.0
o: f1=0.56  p=0.73  r=0.46
20090.0 29787.0
p: f1=0.68  p=0.67  r=0.69
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12756  10335    348   1190]
 [  6815 155451   4908   7518]
 [   507  15601  14538    989]
 [   769   8257    123  20090]]
1020/1020 [==============================] - 486s - train loss: 1.8798   


f1 0.67 - p 0.72 - r 0.64


12554.0 20280.0
i: f1=0.56  p=0.62  r=0.51
157101.0 192229.0
N: f1=0.86  p=0.82  r=0.90
15205.0 21358.0
o: f1=0.57  p=0.71  r=0.48
19031.0 26328.0
p: f1=0.68  p=0.72  r=0.65
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12554  10700    383    992]
 [  6427 157101   5604   5560]
 [   464  15221  15205    745]
 [   835   9207    166  19031]]


- new best score!
Epoch 6 out of 15


1020/1020 [==============================] - 481s - train loss: 1.5000   


f1 0.67 - p 0.72 - r 0.63
Epoch 7 out of 15


10808.0 16375.0
i: f1=0.53  p=0.66  r=0.44
156886.0 191850.0
N: f1=0.86  p=0.82  r=0.90
16721.0 24151.0
o: f1=0.60  p=0.69  r=0.53
19513.0 27819.0
p: f1=0.68  p=0.70  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10808  12196    449   1176]
 [  4650 156886   6776   6380]
 [   328  13836  16721    750]
 [   589   8932    205  19513]]
1020/1020 [==============================] - 365s - train loss: 1.2656   


f1 0.66 - p 0.71 - r 0.62
Epoch 8 out of 15


11401.0 18149.0
i: f1=0.53  p=0.63  r=0.46
157283.0 193333.0
N: f1=0.85  p=0.81  r=0.90
14881.0 20558.0
o: f1=0.57  p=0.72  r=0.47
19466.0 28155.0
p: f1=0.68  p=0.69  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11401  11723    371   1134]
 [  5622 157283   5165   6622]
 [   424  15397  14881    933]
 [   702   8930    141  19466]]
1020/1020 [==============================] - 483s - train loss: 1.0560   


f1 0.65 - p 0.72 - r 0.61
- early stopping 3 epochs without improvement


11058.0 17225.0
i: f1=0.53  p=0.64  r=0.45
158283.0 195968.0
N: f1=0.85  p=0.81  r=0.91
13820.0 18892.0
o: f1=0.55  p=0.73  r=0.44
19412.0 28110.0
p: f1=0.68  p=0.69  r=0.66
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11058  12031    353   1187]
 [  5184 158283   4555   6670]
 [   381  16593  13820    841]
 [   602   9061    164  19412]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 24116 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 15726 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 83 tokens
training
hyperparam for the training below: % 10 k 100


Epoch 1 out of 15


204/204 [==============================] - 128s - train loss: 27.1854   


f1 0.55 - p 0.60 - r 0.51


6444.0 15051.0
i: f1=0.32  p=0.43  r=0.26
155232.0 199816.0
N: f1=0.83  p=0.78  r=0.89
12498.0 21151.0
o: f1=0.47  p=0.59  r=0.40
14781.0 24177.0
p: f1=0.55  p=0.61  r=0.51
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  6444  15174   1228   1783]
 [  5816 155232   6952   6692]
 [   972  17244  12498    921]
 [  1819  12166    473  14781]]


- new best score!
Epoch 2 out of 15


204/204 [==============================] - 123s - train loss: 13.8461   


f1 0.61 - p 0.65 - r 0.59


10870.0 21272.0
i: f1=0.47  p=0.51  r=0.44
152561.0 190068.0
N: f1=0.84  p=0.80  r=0.87
13615.0 20839.0
o: f1=0.52  p=0.65  r=0.43
17738.0 28016.0
p: f1=0.62  p=0.63  r=0.61
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10870  11971    479   1309]
 [  8023 152561   6443   7665]
 [   831  15885  13615   1304]
 [  1548   9651    302  17738]]


- new best score!
Epoch 3 out of 15


204/204 [==============================] - 117s - train loss: 8.8338   


f1 0.62 - p 0.67 - r 0.59


10142.0 17930.0
i: f1=0.48  p=0.57  r=0.41
155233.0 194034.0
N: f1=0.84  p=0.80  r=0.89
13477.0 20215.0
o: f1=0.52  p=0.67  r=0.43
18252.0 28016.0
p: f1=0.64  p=0.65  r=0.62
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10142  12763    469   1255]
 [  6190 155233   5964   7305]
 [   568  16386  13477   1204]
 [  1030   9652    305  18252]]


- new best score!
Epoch 4 out of 15


204/204 [==============================] - 116s - train loss: 6.7750   


f1 0.61 - p 0.67 - r 0.58
Epoch 5 out of 15


10595.0 19294.0
i: f1=0.48  p=0.55  r=0.43
154336.0 193178.0
N: f1=0.84  p=0.80  r=0.88
11485.0 16287.0
o: f1=0.48  p=0.71  r=0.36
19218.0 31436.0
p: f1=0.63  p=0.61  r=0.66
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10595  11979    301   1754]
 [  7099 154336   4303   8954]
 [   814  17826  11485   1510]
 [   786   9037    198  19218]]
204/204 [==============================] - 115s - train loss: 5.3436   


f1 0.57 - p 0.71 - r 0.52
Epoch 6 out of 15


7420.0 12097.0
i: f1=0.40  p=0.61  r=0.30
163751.0 213830.0
N: f1=0.84  p=0.77  r=0.94
9402.0 12948.0
o: f1=0.42  p=0.73  r=0.30
15580.0 21320.0
p: f1=0.62  p=0.73  r=0.53
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  7420  16019    284    906]
 [  3718 163751   3078   4145]
 [   328  21216   9402    689]
 [   631  12844    184  15580]]
204/204 [==============================] - 112s - train loss: 4.2903   


f1 0.56 - p 0.71 - r 0.52
- early stopping 3 epochs without improvement


8127.0 13266.0
i: f1=0.43  p=0.61  r=0.33
163897.0 213978.0
N: f1=0.84  p=0.77  r=0.94
7356.0 9474.0
o: f1=0.36  p=0.78  r=0.23
16544.0 23477.0
p: f1=0.63  p=0.70  r=0.57
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  8127  15352    157    993]
 [  3948 163897   1859   4988]
 [   508  22819   7356    952]
 [   683  11910    102  16544]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 31758 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 19221 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 87 tokens
training
hyperparam for the training below: % 30 k 100


Epoch 1 out of 15


613/613 [==============================] - 303s - train loss: 14.3980   


f1 0.60 - p 0.72 - r 0.54


8599.0 13572.0
i: f1=0.45  p=0.63  r=0.35
162856.0 210028.0
N: f1=0.85  p=0.78  r=0.93
12390.0 17564.0
o: f1=0.50  p=0.71  r=0.39
14793.0 19031.0
p: f1=0.61  p=0.78  r=0.51
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  8599  14903    343    784]
 [  4085 162856   4687   3064]
 [   186  18669  12390    390]
 [   702  13600    144  14793]]


- new best score!
Epoch 2 out of 15


613/613 [==============================] - 302s - train loss: 6.7754   


f1 0.62 - p 0.73 - r 0.56


8945.0 13697.0
i: f1=0.47  p=0.65  r=0.36
163281.0 208636.0
N: f1=0.85  p=0.78  r=0.93
11798.0 15807.0
o: f1=0.50  p=0.75  r=0.37
16577.0 22055.0
p: f1=0.65  p=0.75  r=0.57
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  8945  14270    279   1135]
 [  3944 163281   3644   3823]
 [   193  19124  11798    520]
 [   615  11961     86  16577]]


- new best score!
Epoch 3 out of 15


613/613 [==============================] - 296s - train loss: 4.4130   


f1 0.64 - p 0.71 - r 0.59


9443.0 14405.0
i: f1=0.48  p=0.66  r=0.38
158486.0 198098.0
N: f1=0.85  p=0.80  r=0.91
14905.0 21757.0
o: f1=0.56  p=0.69  r=0.47
17936.0 25935.0
p: f1=0.65  p=0.69  r=0.61
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  9443  13151    430   1605]
 [  4192 158486   6259   5755]
 [   251  15840  14905    639]
 [   519  10621    163  17936]]


- new best score!
Epoch 4 out of 15


613/613 [==============================] - 310s - train loss: 3.2112   


f1 0.64 - p 0.73 - r 0.59


9685.0 14807.0
i: f1=0.49  p=0.65  r=0.39
160323.0 200916.0
N: f1=0.85  p=0.80  r=0.92
15316.0 21993.0
o: f1=0.57  p=0.70  r=0.48
17037.0 22479.0
p: f1=0.66  p=0.76  r=0.58
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  9685  13651    351    942]
 [  4274 160323   6134   3961]
 [   231  15549  15316    539]
 [   617  11393    192  17037]]


- new best score!
Epoch 5 out of 15


613/613 [==============================] - 299s - train loss: 2.6147   


f1 0.66 - p 0.71 - r 0.62


11211.0 18151.0
i: f1=0.52  p=0.62  r=0.46
156979.0 193838.0
N: f1=0.85  p=0.81  r=0.90
17064.0 25837.0
o: f1=0.59  p=0.66  r=0.54
16985.0 22369.0
p: f1=0.66  p=0.76  r=0.58
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11211  12058    502    858]
 [  5674 156979   8026   4013]
 [   381  13677  17064    513]
 [   885  11124    245  16985]]


- new best score!
Epoch 6 out of 15


613/613 [==============================] - 235s - train loss: 2.0134   


f1 0.66 - p 0.72 - r 0.61
Epoch 7 out of 15


11267.0 18223.0
i: f1=0.53  p=0.62  r=0.46
157653.0 195116.0
N: f1=0.85  p=0.81  r=0.90
16888.0 25248.0
o: f1=0.59  p=0.67  r=0.53
16549.0 21608.0
p: f1=0.65  p=0.77  r=0.57
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11267  12061    488    813]
 [  5733 157653   7550   3756]
 [   411  13846  16888    490]
 [   812  11556    322  16549]]
613/613 [==============================] - 369s - train loss: 1.6261   


f1 0.65 - p 0.72 - r 0.61
Epoch 8 out of 15


10186.0 15283.0
i: f1=0.51  p=0.67  r=0.41
159039.0 197464.0
N: f1=0.85  p=0.81  r=0.91
16010.0 23131.0
o: f1=0.58  p=0.69  r=0.51
17750.0 24317.0
p: f1=0.66  p=0.73  r=0.61
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10186  13014    406   1023]
 [  4292 159039   6493   4868]
 [   299  14650  16010    676]
 [   506  10761    222  17750]]
613/613 [==============================] - 316s - train loss: 1.3846   


f1 0.65 - p 0.72 - r 0.61
- early stopping 3 epochs without improvement


10840.0 16811.0
i: f1=0.52  p=0.64  r=0.44
159077.0 197857.0
N: f1=0.85  p=0.80  r=0.91
16476.0 24245.0
o: f1=0.59  p=0.68  r=0.52
16271.0 21282.0
p: f1=0.64  p=0.76  r=0.56
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10840  12464    474    851]
 [  4910 159077   7022   3683]
 [   381  14301  16476    477]
 [   680  12015    273  16271]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 36357 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 21074 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 88 tokens
training
hyperparam for the training below: % 50 k 100


Epoch 1 out of 15


1020/1020 [==============================] - 470s - train loss: 10.2458   


f1 0.63 - p 0.70 - r 0.59


10010.0 15887.0
i: f1=0.49  p=0.63  r=0.41
157407.0 197621.0
N: f1=0.85  p=0.80  r=0.90
14623.0 21897.0
o: f1=0.55  p=0.67  r=0.46
17445.0 24790.0
p: f1=0.65  p=0.70  r=0.60
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10010  13010    482   1127]
 [  5161 157407   6582   5542]
 [   229  16107  14623    676]
 [   487  11097    210  17445]]


- new best score!
Epoch 2 out of 15


1020/1020 [==============================] - 419s - train loss: 4.4414   


f1 0.64 - p 0.72 - r 0.60


9388.0 13868.0
i: f1=0.49  p=0.68  r=0.38
158642.0 198245.0
N: f1=0.85  p=0.80  r=0.91
16509.0 25253.0
o: f1=0.58  p=0.65  r=0.52
17180.0 22829.0
p: f1=0.66  p=0.75  r=0.59
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  9388  13849    487    905]
 [  3822 158642   8073   4155]
 [   258  14279  16509    589]
 [   400  11475    184  17180]]


- new best score!
Epoch 3 out of 15


1020/1020 [==============================] - 464s - train loss: 2.8545   


f1 0.66 - p 0.71 - r 0.62


11738.0 19040.0
i: f1=0.54  p=0.62  r=0.48
156620.0 192897.0
N: f1=0.85  p=0.81  r=0.90
16269.0 24106.0
o: f1=0.58  p=0.67  r=0.51
17897.0 24152.0
p: f1=0.67  p=0.74  r=0.61
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11738  11514    475    902]
 [  6181 156620   7185   4706]
 [   324  14395  16269    647]
 [   797  10368    177  17897]]


- new best score!
Epoch 4 out of 15


1020/1020 [==============================] - 465s - train loss: 2.0796   


f1 0.66 - p 0.72 - r 0.63


12760.0 21559.0
i: f1=0.55  p=0.59  r=0.52
157036.0 192999.0
N: f1=0.85  p=0.81  r=0.90
15829.0 22574.0
o: f1=0.58  p=0.70  r=0.50
17427.0 23063.0
p: f1=0.67  p=0.76  r=0.60
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12760  10735    395    739]
 [  7182 157036   6202   4272]
 [   498  14683  15829    625]
 [  1119  10545    148  17427]]


- new best score!
Epoch 5 out of 15


1020/1020 [==============================] - 461s - train loss: 1.6067   


f1 0.67 - p 0.73 - r 0.63


11342.0 17475.0
i: f1=0.54  p=0.65  r=0.46
158053.0 194663.0
N: f1=0.86  p=0.81  r=0.90
17653.0 26927.0
o: f1=0.60  p=0.66  r=0.56
16980.0 21130.0
p: f1=0.67  p=0.80  r=0.58
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11342  12002    624    661]
 [  5196 158053   8323   3120]
 [   247  13366  17653    369]
 [   690  11242    327  16980]]


- new best score!
Epoch 6 out of 15


1020/1020 [==============================] - 484s - train loss: 1.3274   


f1 0.67 - p 0.71 - r 0.65


12565.0 21035.0
i: f1=0.55  p=0.60  r=0.51
153679.0 186584.0
N: f1=0.85  p=0.82  r=0.88
19067.0 30872.0
o: f1=0.61  p=0.62  r=0.60
17186.0 21704.0
p: f1=0.67  p=0.79  r=0.59
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12565  10673    726    665]
 [  6954 153679  10706   3353]
 [   413  11655  19067    500]
 [  1103  10577    373  17186]]


- new best score!
Epoch 7 out of 15


1020/1020 [==============================] - 459s - train loss: 1.0737   


f1 0.67 - p 0.71 - r 0.64
Epoch 8 out of 15


12231.0 19862.0
i: f1=0.55  p=0.62  r=0.50
154577.0 188115.0
N: f1=0.85  p=0.82  r=0.88
18097.0 28146.0
o: f1=0.61  p=0.64  r=0.57
17988.0 24072.0
p: f1=0.67  p=0.75  r=0.62
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12231  10992    560    846]
 [  6220 154577   9215   4680]
 [   449  12531  18097    558]
 [   962  10015    274  17988]]
1020/1020 [==============================] - 334s - train loss: 0.9118   


f1 0.67 - p 0.72 - r 0.64


12247.0 19600.0
i: f1=0.55  p=0.62  r=0.50
156082.0 190305.0
N: f1=0.86  p=0.82  r=0.89
17372.0 26139.0
o: f1=0.60  p=0.66  r=0.55
18208.0 24151.0
p: f1=0.68  p=0.75  r=0.62
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12247  10942    537    903]
 [  6200 156082   7945   4465]
 [   377  13311  17372    575]
 [   776   9970    285  18208]]


- new best score!
Epoch 9 out of 15


1020/1020 [==============================] - 445s - train loss: 0.7797   


f1 0.67 - p 0.71 - r 0.63
Epoch 10 out of 15


11275.0 17486.0
i: f1=0.54  p=0.64  r=0.46
156578.0 191520.0
N: f1=0.86  p=0.82  r=0.90
16732.0 24421.0
o: f1=0.60  p=0.69  r=0.53
18925.0 26768.0
p: f1=0.68  p=0.71  r=0.65
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11275  11648    543   1163]
 [  5225 156578   6871   6018]
 [   297  13944  16732    662]
 [   689   9350    275  18925]]
1020/1020 [==============================] - 461s - train loss: 0.7137   


f1 0.67 - p 0.70 - r 0.64
Epoch 11 out of 15


12350.0 20278.0
i: f1=0.55  p=0.61  r=0.50
154742.0 188284.0
N: f1=0.85  p=0.82  r=0.89
16324.0 23852.0
o: f1=0.59  p=0.68  r=0.52
19325.0 27781.0
p: f1=0.68  p=0.70  r=0.66
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12350  10669    430   1180]
 [  6580 154742   6858   6512]
 [   465  14082  16324    764]
 [   883   8791    240  19325]]
1020/1020 [==============================] - 486s - train loss: 0.6186   


f1 0.67 - p 0.71 - r 0.64
- early stopping 3 epochs without improvement


11675.0 18498.0
i: f1=0.54  p=0.63  r=0.47
155899.0 190122.0
N: f1=0.85  p=0.82  r=0.89
16468.0 24105.0
o: f1=0.59  p=0.68  r=0.52
19275.0 27470.0
p: f1=0.68  p=0.70  r=0.66
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11675  11196    486   1272]
 [  5721 155899   6907   6165]
 [   371  14038  16468    758]
 [   731   8989    244  19275]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 23997 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 15699 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 85 tokens
training
hyperparam for the training below: % 10 k 200


Epoch 1 out of 15


205/205 [==============================] - 139s - train loss: 32.2491   


f1 0.47 - p 0.64 - r 0.44


1785.0 2983.0
i: f1=0.13  p=0.60  r=0.07
162117.0 218457.0
N: f1=0.82  p=0.74  r=0.93
11124.0 21823.0
o: f1=0.42  p=0.51  r=0.35
11903.0 16932.0
p: f1=0.52  p=0.70  r=0.41
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  1785  20387   1500    957]
 [   842 162117   8284   3449]
 [   157  19731  11124    623]
 [   199  16222    915  11903]]


- new best score!
Epoch 2 out of 15


205/205 [==============================] - 149s - train loss: 15.9289   


f1 0.56 - p 0.67 - r 0.52


5708.0 9212.0
i: f1=0.34  p=0.62  r=0.23
159877.0 207450.0
N: f1=0.84  p=0.77  r=0.92
12499.0 19901.0
o: f1=0.49  p=0.63  r=0.40
15713.0 23632.0
p: f1=0.59  p=0.66  r=0.54
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  5708  17113    682   1126]
 [  2849 159877   6354   5612]
 [   254  17701  12499   1181]
 [   401  12759    366  15713]]


- new best score!
Epoch 3 out of 15


205/205 [==============================] - 127s - train loss: 10.4016   


f1 0.60 - p 0.68 - r 0.55


9010.0 15530.0
i: f1=0.45  p=0.58  r=0.37
158418.0 202576.0
N: f1=0.84  p=0.78  r=0.91
13947.0 22006.0
o: f1=0.52  p=0.63  r=0.44
14560.0 20083.0
p: f1=0.59  p=0.72  r=0.50
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  9010  14271    606    742]
 [  5289 158418   7004   3981]
 [   575  16313  13947    800]
 [   656  13574    449  14560]]


- new best score!
Epoch 4 out of 15


205/205 [==============================] - 127s - train loss: 7.8579   


f1 0.60 - p 0.70 - r 0.55
Epoch 5 out of 15


7762.0 12385.0
i: f1=0.42  p=0.63  r=0.32
159234.0 203766.0
N: f1=0.84  p=0.78  r=0.91
15786.0 25642.0
o: f1=0.55  p=0.62  r=0.50
13937.0 18402.0
p: f1=0.59  p=0.76  r=0.48
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  7762  15374    788    705]
 [  3845 159234   8415   3198]
 [   372  14915  15786    562]
 [   406  14243    653  13937]]
205/205 [==============================] - 127s - train loss: 6.2036   


f1 0.58 - p 0.71 - r 0.53
Epoch 6 out of 15


6004.0 8845.0
i: f1=0.36  p=0.68  r=0.24
159431.0 205803.0
N: f1=0.84  p=0.77  r=0.91
17465.0 30357.0
o: f1=0.56  p=0.58  r=0.55
12122.0 15190.0
p: f1=0.55  p=0.80  r=0.41
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  6004  16939   1140    546]
 [  2326 159431  10767   2168]
 [   201  13615  17465    354]
 [   314  15818    985  12122]]
205/205 [==============================] - 128s - train loss: 4.9976   


f1 0.60 - p 0.69 - r 0.56
- early stopping 3 epochs without improvement


6469.0 9602.0
i: f1=0.38  p=0.67  r=0.26
156747.0 198782.0
N: f1=0.84  p=0.79  r=0.90
18183.0 32071.0
o: f1=0.57  p=0.57  r=0.57
14586.0 19740.0
p: f1=0.60  p=0.74  r=0.50
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  6469  16018   1258    884]
 [  2554 156747  11690   3701]
 [   265  12618  18183    569]
 [   314  13399    940  14586]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 31342 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 18996 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 87 tokens
training
hyperparam for the training below: % 30 k 200


Epoch 1 out of 15


612/612 [==============================] - 307s - train loss: 16.1817   


f1 0.54 - p 0.73 - r 0.50


4477.0 6036.0
i: f1=0.29  p=0.74  r=0.18
164228.0 215031.0
N: f1=0.84  p=0.76  r=0.94
9050.0 12000.0
o: f1=0.41  p=0.75  r=0.29
17432.0 27128.0
p: f1=0.62  p=0.64  r=0.60
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  4477  18034    184   1934]
 [  1259 164228   2639   6566]
 [    98  21291   9050   1196]
 [   202  11478    127  17432]]


- new best score!
Epoch 2 out of 15


612/612 [==============================] - 307s - train loss: 7.2588   


f1 0.61 - p 0.71 - r 0.56


7950.0 11496.0
i: f1=0.44  p=0.69  r=0.32
160009.0 202949.0
N: f1=0.85  p=0.79  r=0.92
11845.0 16375.0
o: f1=0.49  p=0.72  r=0.37
18759.0 29375.0
p: f1=0.64  p=0.64  r=0.64
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  7950  14163    302   2214]
 [  3087 160009   4053   7543]
 [   164  18767  11845    859]
 [   295  10010    175  18759]]


- new best score!
Epoch 3 out of 15


612/612 [==============================] - 215s - train loss: 4.7679   


f1 0.63 - p 0.74 - r 0.58


8824.0 12877.0
i: f1=0.47  p=0.69  r=0.36
162654.0 206044.0
N: f1=0.85  p=0.79  r=0.93
13333.0 18124.0
o: f1=0.54  p=0.74  r=0.42
17268.0 23150.0
p: f1=0.66  p=0.75  r=0.59
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  8824  14395    260   1150]
 [  3516 162654   4357   4165]
 [   216  17519  13333    567]
 [   321  11476    174  17268]]


- new best score!
Epoch 4 out of 15


612/612 [==============================] - 282s - train loss: 3.4797   


f1 0.65 - p 0.72 - r 0.60


9582.0 14324.0
i: f1=0.49  p=0.67  r=0.39
158910.0 198214.0
N: f1=0.85  p=0.80  r=0.91
16331.0 24310.0
o: f1=0.58  p=0.67  r=0.52
17180.0 23347.0
p: f1=0.65  p=0.74  r=0.59
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  9582  13386    492   1169]
 [  4158 158910   7209   4415]
 [   206  14515  16331    583]
 [   378  11403    278  17180]]


- new best score!
Epoch 5 out of 15


612/612 [==============================] - 311s - train loss: 2.6811   


f1 0.65 - p 0.72 - r 0.60


10219.0 15921.0
i: f1=0.50  p=0.64  r=0.41
158947.0 198515.0
N: f1=0.85  p=0.80  r=0.91
16400.0 24440.0
o: f1=0.58  p=0.67  r=0.52
16255.0 21319.0
p: f1=0.64  p=0.76  r=0.56
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 10219  12821    560   1029]
 [  4989 158947   7221   3535]
 [   240  14495  16400    500]
 [   473  12252    259  16255]]


- new best score!
Epoch 6 out of 15


612/612 [==============================] - 312s - train loss: 2.1266   


f1 0.65 - p 0.71 - r 0.62


11814.0 19208.0
i: f1=0.54  p=0.62  r=0.48
157171.0 194108.0
N: f1=0.85  p=0.81  r=0.90
13940.0 19421.0
o: f1=0.55  p=0.72  r=0.44
19021.0 27458.0
p: f1=0.67  p=0.69  r=0.65
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11814  10907    396   1512]
 [  6437 157171   4888   6196]
 [   312  16654  13940    729]
 [   645   9376    197  19021]]


- new best score!
Epoch 7 out of 15


612/612 [==============================] - 243s - train loss: 1.7836   


f1 0.65 - p 0.72 - r 0.60
Epoch 8 out of 15


11310.0 18564.0
i: f1=0.52  p=0.61  r=0.46
159090.0 198272.0
N: f1=0.85  p=0.80  r=0.91
14603.0 20393.0
o: f1=0.56  p=0.72  r=0.46
17002.0 22966.0
p: f1=0.65  p=0.74  r=0.58
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11310  11737    429   1153]
 [  6197 159090   5154   4251]
 [   361  16111  14603    560]
 [   696  11334    207  17002]]
612/612 [==============================] - 244s - train loss: 1.4793   


f1 0.66 - p 0.70 - r 0.63


11469.0 18989.0
i: f1=0.53  p=0.60  r=0.47
154951.0 190103.0
N: f1=0.85  p=0.82  r=0.89
16652.0 25300.0
o: f1=0.58  p=0.66  r=0.53
18188.0 25803.0
p: f1=0.66  p=0.70  r=0.62
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11469  11256    588   1316]
 [  6406 154951   7723   5612]
 [   365  13931  16652    687]
 [   749   9965    337  18188]]


- new best score!
Epoch 9 out of 15


612/612 [==============================] - 305s - train loss: 1.2594   


f1 0.66 - p 0.69 - r 0.64


12095.0 20030.0
i: f1=0.54  p=0.60  r=0.49
153635.0 187050.0
N: f1=0.85  p=0.82  r=0.88
16119.0 23701.0
o: f1=0.58  p=0.68  r=0.51
19570.0 29414.0
p: f1=0.67  p=0.67  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12095  10430    489   1615]
 [  6822 153635   6855   7380]
 [   425  14242  16119    849]
 [   688   8743    238  19570]]


- new best score!
Epoch 10 out of 15


612/612 [==============================] - 306s - train loss: 1.0930   


f1 0.66 - p 0.70 - r 0.63
Epoch 11 out of 15


11711.0 19387.0
i: f1=0.53  p=0.60  r=0.48
155075.0 190000.0
N: f1=0.85  p=0.82  r=0.89
16196.0 24037.0
o: f1=0.58  p=0.67  r=0.51
18705.0 26771.0
p: f1=0.67  p=0.70  r=0.64
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11711  11075    584   1259]
 [  6481 155075   7004   6132]
 [   413  14351  16196    675]
 [   782   9499    253  18705]]
612/612 [==============================] - 308s - train loss: 0.9664   


f1 0.66 - p 0.70 - r 0.64


11181.0 17658.0
i: f1=0.53  p=0.63  r=0.45
154091.0 187475.0
N: f1=0.85  p=0.82  r=0.88
17306.0 26286.0
o: f1=0.60  p=0.66  r=0.55
19396.0 28776.0
p: f1=0.67  p=0.67  r=0.66
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11181  11307    637   1504]
 [  5522 154091   8013   7066]
 [   405  13114  17306    810]
 [   550   8963    330  19396]]


- new best score!
Epoch 12 out of 15


612/612 [==============================] - 307s - train loss: 0.8529   


f1 0.66 - p 0.70 - r 0.64


11579.0 18450.0
i: f1=0.54  p=0.63  r=0.47
154782.0 188448.0
N: f1=0.85  p=0.82  r=0.89
17437.0 26926.0
o: f1=0.60  p=0.65  r=0.55
18605.0 26371.0
p: f1=0.67  p=0.71  r=0.64
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11579  11080    702   1268]
 [  5768 154782   8382   5760]
 [   456  13004  17437    738]
 [   647   9582    405  18605]]


- new best score!
Epoch 13 out of 15


612/612 [==============================] - 308s - train loss: 0.7511   


f1 0.66 - p 0.71 - r 0.63
Epoch 14 out of 15


11162.0 17554.0
i: f1=0.53  p=0.64  r=0.45
156019.0 191037.0
N: f1=0.85  p=0.82  r=0.89
17472.0 26712.0
o: f1=0.60  p=0.65  r=0.55
18025.0 24892.0
p: f1=0.67  p=0.72  r=0.62
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11162  11506    715   1246]
 [  5509 156019   8156   5008]
 [   375  13175  17472    613]
 [   508  10337    369  18025]]
612/612 [==============================] - 306s - train loss: 0.6729   


f1 0.66 - p 0.70 - r 0.64
Epoch 15 out of 15


11106.0 17367.0
i: f1=0.53  p=0.64  r=0.45
154004.0 187082.0
N: f1=0.85  p=0.82  r=0.88
17533.0 26840.0
o: f1=0.60  p=0.65  r=0.55
19492.0 28906.0
p: f1=0.67  p=0.67  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11106  11206    709   1608]
 [  5440 154004   8223   7025]
 [   340  12981  17533    781]
 [   481   8891    375  19492]]
612/612 [==============================] - 322s - train loss: 0.6105   


f1 0.66 - p 0.70 - r 0.64


11391.0 18141.0
i: f1=0.53  p=0.63  r=0.46
153797.0 186780.0
N: f1=0.85  p=0.82  r=0.88
17973.0 27982.0
o: f1=0.60  p=0.64  r=0.57
18973.0 27292.0
p: f1=0.67  p=0.70  r=0.65
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11391  11105    749   1384]
 [  5807 153797   8817   6271]
 [   380  12618  17973    664]
 [   563   9260    443  18973]]


- new best score!


Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session


Processing_word
Building vocab...
- done. 36105 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 20961 tokens
Writing vocab...
- done. 4 tokens
Writing vocab...
- done. 88 tokens
training
hyperparam for the training below: % 50 k 200


Epoch 1 out of 15


1021/1021 [==============================] - 393s - train loss: 14.6299   


f1 0.64 - p 0.66 - r 0.64


13214.0 25271.0
i: f1=0.53  p=0.52  r=0.54
147356.0 178552.0
N: f1=0.83  p=0.83  r=0.84
14497.0 21362.0
o: f1=0.55  p=0.68  r=0.46
20777.0 35010.0
p: f1=0.65  p=0.59  r=0.71
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 13214   9188    350   1877]
 [ 10051 147356   6323  10962]
 [  1016  14728  14497   1394]
 [   990   7280    192  20777]]


- new best score!
Epoch 2 out of 15


1021/1021 [==============================] - 499s - train loss: 5.8695   


f1 0.65 - p 0.69 - r 0.62


11470.0 19558.0
i: f1=0.52  p=0.59  r=0.47
153585.0 188385.0
N: f1=0.85  p=0.82  r=0.88
14828.0 21288.0
o: f1=0.56  p=0.70  r=0.47
19953.0 30964.0
p: f1=0.66  p=0.64  r=0.68
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11470  11016    340   1803]
 [  6897 153585   5934   8276]
 [   492  15383  14828    932]
 [   699   8401    186  19953]]


- new best score!
Epoch 3 out of 15


1021/1021 [==============================] - 475s - train loss: 3.5806   


f1 0.65 - p 0.72 - r 0.61


13024.0 22904.0
i: f1=0.55  p=0.57  r=0.53
157736.0 196480.0
N: f1=0.85  p=0.80  r=0.90
15653.0 22965.0
o: f1=0.57  p=0.68  r=0.49
14574.0 17846.0
p: f1=0.62  p=0.82  r=0.50
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 13024  10711    404    490]
 [  7945 157736   6638   2373]
 [   684  14889  15653    409]
 [  1251  13144    270  14574]]


- new best score!
Epoch 4 out of 15


1021/1021 [==============================] - 476s - train loss: 2.5509   


f1 0.64 - p 0.74 - r 0.59
Epoch 5 out of 15


9082.0 13209.0
i: f1=0.48  p=0.69  r=0.37
160247.0 200811.0
N: f1=0.85  p=0.80  r=0.92
17528.0 26507.0
o: f1=0.60  p=0.66  r=0.55
15713.0 19668.0
p: f1=0.64  p=0.80  r=0.54
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  9082  14282    552    713]
 [  3486 160247   8116   2843]
 [   186  13522  17528    399]
 [   455  12760    311  15713]]
1021/1021 [==============================] - 475s - train loss: 1.9103   


f1 0.66 - p 0.72 - r 0.62


9594.0 14048.0
i: f1=0.50  p=0.68  r=0.39
157531.0 194198.0
N: f1=0.85  p=0.81  r=0.90
18264.0 28567.0
o: f1=0.61  p=0.64  r=0.58
17575.0 23382.0
p: f1=0.67  p=0.75  r=0.60
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[  9594  13239    639   1157]
 [  3795 157531   9203   4163]
 [   242  12642  18264    487]
 [   417  10786    461  17575]]


- new best score!
Epoch 6 out of 15


1021/1021 [==============================] - 475s - train loss: 1.5283   


f1 0.67 - p 0.71 - r 0.63


11276.0 17833.0
i: f1=0.53  p=0.63  r=0.46
156841.0 191603.0
N: f1=0.86  p=0.82  r=0.90
17051.0 25089.0
o: f1=0.60  p=0.68  r=0.54
18685.0 25670.0
p: f1=0.68  p=0.73  r=0.64
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11276  11501    538   1314]
 [  5636 156841   7208   5007]
 [   302  13618  17051    664]
 [   619   9643    292  18685]]


- new best score!
Epoch 7 out of 15


1021/1021 [==============================] - 473s - train loss: 1.3287   


f1 0.67 - p 0.70 - r 0.65


14020.0 25470.0
i: f1=0.56  p=0.55  r=0.57
153760.0 186500.0
N: f1=0.85  p=0.82  r=0.88
15057.0 20834.0
o: f1=0.57  p=0.72  r=0.48
19436.0 27391.0
p: f1=0.69  p=0.71  r=0.66
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 14020   9071    394   1144]
 [  9604 153760   5215   6113]
 [   619  15261  15057    698]
 [  1227   8408    168  19436]]


- new best score!
Epoch 8 out of 15


1021/1021 [==============================] - 474s - train loss: 1.1004   


f1 0.65 - p 0.70 - r 0.63
Epoch 9 out of 15


11992.0 19697.0
i: f1=0.54  p=0.61  r=0.49
155268.0 190243.0
N: f1=0.85  p=0.82  r=0.89
13901.0 18620.0
o: f1=0.55  p=0.75  r=0.44
20448.0 31635.0
p: f1=0.67  p=0.65  r=0.70
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 11992  10534    318   1785]
 [  6657 155268   4272   8495]
 [   391  16436  13901    907]
 [   657   8005    129  20448]]
1021/1021 [==============================] - 286s - train loss: 0.9153   


f1 0.66 - p 0.71 - r 0.63
Epoch 10 out of 15


12143.0 20059.0
i: f1=0.54  p=0.61  r=0.49
156156.0 191391.0
N: f1=0.85  p=0.82  r=0.89
14893.0 20755.0
o: f1=0.57  p=0.72  r=0.47
19454.0 27990.0
p: f1=0.68  p=0.70  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 12143  10703    404   1379]
 [  6763 156156   5283   6490]
 [   429  15646  14893    667]
 [   724   8886    175  19454]]
1021/1021 [==============================] - 256s - train loss: 0.7825   


f1 0.67 - p 0.70 - r 0.65
- early stopping 3 epochs without improvement


13238.0 22884.0
i: f1=0.56  p=0.58  r=0.54
153191.0 185591.0
N: f1=0.85  p=0.83  r=0.88
15899.0 22785.0
o: f1=0.58  p=0.70  r=0.50
19710.0 28935.0
p: f1=0.68  p=0.68  r=0.67
Confusion matrix: 
 rows: true labels (the order is the same as in /data/tags.txt) 
 columns: predicted labels (the order is the same as in /data/tags.txt)
[[ 13238   9604    445   1342]
 [  8178 153191   6228   7095]
 [   521  14427  15899    788]
 [   947   8369    213  19710]]
Config


/home/masha/anaconda3/envs/my_tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Initializing tf session
